module Graft
  class Callback
    include Callable

    type options = Hash[Symbol, untyped]

    @opts: options

    @block: untyped

    @enabled: bool

    attr_reader name: String

    def initialize: (?untyped? name, ?options opts) { (Stack stack, Stack::env env) -> Stack::ret } -> void

    def disable: () -> void

    def enable: () -> void

    def enabled?: () -> bool
  end
end
