# frozen_string_literal: true

# @type self: Rake::DSL

namespace :docker do
  namespace :compose do
    desc "Generate docker-compose.yml"
    task :generate do |_task, args|
      check = args.to_a.include?("check")

      require "psych"
      require "open3"

      images = Dir.glob(File.join("images", "**", "*.dockerfile"))

      docker_compose = images.each_with_object({"services" => {}, "volumes" => {}}) do |image, compose|
        ruby = File.basename(image, ".dockerfile")
        version = ruby =~ /(\d+\.\d+)$/ && $1

        compose["services"][ruby] = {
          "build" => {
            "context" => ".",
            "dockerfile" => image
          },
          "command" => "/bin/bash",
          "environment" => {
            "BUNDLE_GEMFILE" => "gemfiles/#{ruby}.gemfile"
          },
          "stdin_open" => true,
          "tty" => true,
          "volumes" => [
            ".:/app",
            "bundle-#{version}:/usr/local/bundle"
          ]
        }

        compose["volumes"]["bundle-#{version}"] = nil
      end

      target = "docker-compose.yml"

      original = File.binread(target)

      new = +""
      new << <<~EOS
        # Please do NOT manually edit this file.
        # This file is generated by 'bundle exec rake docker:compose:generate'
      EOS
      new << Psych.dump(docker_compose)

      if original == new
        puts "No changes. '#{target}' is up-to-date."
      elsif check
        puts "'#{target}' has changed. Please review the changes and commit."

        require "tmpdir"

        Dir.mktmpdir do |d|
          Dir.chdir(d) do
            File.binwrite(target + ".orig", original)
            File.binwrite(target, new)
            sh "git diff --color #{target}.orig #{target}"
          end
        end

        exit 1
      else
        File.binwrite(target, new)
        puts "'#{target}' has been updated. Please review the changes below:\n\n"
        sh "git diff --color #{target}"
      end
    end
  end
end
