module Graft
  class Hook
    module Wrapper : Hook
    # def wrapper: (Hook hook) -> (^(*untyped args) -> untyped)
      def wrapper: (Hook hook) -> (^(*untyped args, **untyped kwargs) -> untyped)
    end
  end
end
