name: Check

on:
  push:

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.1"
        bundler-cache: true
    - name: Lint with StandardRB
      run: bundle exec rake standard
    - name: Lint with Rubocop
      run: bundle exec rake rubocop
    - name: Check types
      # TODO: swallowing result until types pass
      run: bundle exec rake steep:check || true
