name: Check

on:
  push:
  workflow_call:

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/datadog/images-rb/engines/ruby:3.3"

    steps:
    - uses: actions/checkout@v4
    - name: Bundle install
      run: bundle install
    - name: Bundle list
      run: bundle show
    - name: Lockfile
      run: cat Gemfile.lock
    - name: Lint with StandardRB
      run: bundle exec rake standard
    - name: Lint with Rubocop
      run: bundle exec rake rubocop
    - name: Check types
      run: |
        bundle exec rbs collection install
        # TODO: swallowing result until types pass
        bundle exec rake steep:check
    - name: Check generators
      run: |
        bundle exec rake docker:compose:generate[check]
