name: Lint

on:
  push:

jobs:
  lint:
    name: Standard Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.1"
        bundler-cache: true
    - name: Run the lint task
      run: bundle exec rake standard
