name: Publish Gem

on: workflow_dispatch

jobs:
  check:
    uses: ./.github/workflows/check.yml

  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    environment: release
    needs:
      - check
      - test
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2.4'
      - uses: rubygems/release-gem@v1
