name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        # Find the versions available at https://github.com/ruby/setup-ruby/blob/master/ruby-builder-versions.json
        ruby:
          - '3.3.1'
          - '3.2.4'
          - '3.1.5'
          - '3.0.6'
          - '2.7.8'
          - '2.6.10'
          - '2.5.9'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the test
      run: bundle exec rake test
