name: Unit Test

on:
  schedule:
    - cron: '0 7 * * *'
  push:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with ${{ matrix.ruby }}
    strategy:
      matrix:
        # Find the versions available at https://github.com/ruby/setup-ruby/blob/master/ruby-builder-versions.json
        ruby:
          - '3.3.1'
          - '3.2.4'
          - '3.1.5'
          - '3.0.6'
          - '2.7.8'
          - '2.6.10'
          - '2.5.9'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the test
        run: bundle exec rake test spec

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: always() && github.event_name == 'schedule'
    steps:
      - if: ${{ needs.test.result == 'success' }}
        name: Notify on success
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ vars.SLACK_CHANNEL_ID }}
          slack-message: |-
            :github: ${{ github.repository }}: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            :github-check: ${{ github.ref_type }}: ${{ github.ref_name }}
      - if: ${{ needs.test.result == 'failure' }}
        name: Notify on failure
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ vars.SLACK_CHANNEL_ID }}
          slack-message: |-
            :github: ${{ github.repository }}: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            :red-light: ${{ github.ref_type }}: ${{ github.ref_name }}
