name: Unit Test

on:
  push:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with ${{ matrix.ruby }}
    strategy:
      matrix:
        engine:
          - name: ruby
            version:
              - '3.4'
              - '3.3'
              - '3.2'
              - '3.1'
              - '3.0'
              - '2.7'
              - '2.6'
              - '2.5'
          - name: jruby
            version:
              - '9.4'
              - '9.3'
              - '9.2'
    image: "ghcr.io/datadog/images-rb/engines/${{ matrix.engine.name }}:${{ matrix.engine.version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Bundle install
        run: bundle install
      - name: Run the test
        run: bundle exec rake test spec
